### ISSUE TITLE
Mod doesnt seem to be working

### ISSUE THREAD

**Issue by GreeeM** [The-Black-Lodge/JowdayBookDuringBoonSelect#5]
![image_2024-06-09_200314688](https://github.com/The-Black-Lodge/JowdayBoonBuddy/assets/54411118/7cc9a29e-cd5c-4a26-b1b8-e694e538909c)

 option is set to only allow purple and up but i keep getting different rarities as per the picture

**Comment by southpawgeek** [comment]
@GreeeM would you mind attaching your save file? Currently it won't apply to fresh save files for at least 2 runs.

It'll probably be in somewhere like
C:/Users/YourUsername/Saved Games/Hades II

and it'll be a filename like Profile1.sav, if you're using the first save slot.

**Comment by southpawgeek** [comment]
I also have a report of rarity not working properly in Surface runs, so I am looking into this

**Comment by GreeeM** [comment]
https://filetransfer.io/data-package/V4OXgVfE#link   This site okey?

Installed the mod after i took down chronos, so it weren't a fresh save. think i just completed my 2nd run with the mod running so ill  hop back in to try it again now.

**Comment by GreeeM** [comment]
Hopped in and just died twice in a row quick to try it. and still getting mostly basic boons.

**Comment by southpawgeek** [comment]
Yup, that's fine. Thank you! I'll take a look. Seems to be something strange going on with the Surface?

Also, what other mods are you running? I don't think any of them conflict, but just for completeness.

If you use Discord we have a channel called #help-h2, might be quicker to communicate in there https://discord.com/invite/KuMbyrN

**Comment by southpawgeek** [comment]
Issue should now be resolved in 0.6.4 - thank you for the report and see you in Discord!
